// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoP3DCfB0LQZe4fRxK1tDjo3KdVu3ZvxA',
    appId: '1:130831722796:web:1a05dfcb4d50fb9d9fe489',
    messagingSenderId: '130831722796',
    projectId: 'modul3-64c3b',
    authDomain: 'modul3-64c3b.firebaseapp.com',
    storageBucket: 'modul3-64c3b.appspot.com',
    measurementId: 'G-LS13VM1RFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqzO3JC7m67U2_Sv0Ehlel1DVb2V0qbEY',
    appId: '1:130831722796:android:b0ce746e2cb710119fe489',
    messagingSenderId: '130831722796',
    projectId: 'modul3-64c3b',
    storageBucket: 'modul3-64c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4amJwb1yZA6hm19VgCzdCjWWQmOfU1Rc',
    appId: '1:130831722796:ios:58310af4f7eecb239fe489',
    messagingSenderId: '130831722796',
    projectId: 'modul3-64c3b',
    storageBucket: 'modul3-64c3b.appspot.com',
    iosBundleId: 'com.example.coba3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4amJwb1yZA6hm19VgCzdCjWWQmOfU1Rc',
    appId: '1:130831722796:ios:58310af4f7eecb239fe489',
    messagingSenderId: '130831722796',
    projectId: 'modul3-64c3b',
    storageBucket: 'modul3-64c3b.appspot.com',
    iosBundleId: 'com.example.coba3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoP3DCfB0LQZe4fRxK1tDjo3KdVu3ZvxA',
    appId: '1:130831722796:web:065fb35cc7e48fb79fe489',
    messagingSenderId: '130831722796',
    projectId: 'modul3-64c3b',
    authDomain: 'modul3-64c3b.firebaseapp.com',
    storageBucket: 'modul3-64c3b.appspot.com',
    measurementId: 'G-JMETYV4MZD',
  );
}
